/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type HomeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "home";
};

export type AboutReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "about";
};

export type MediaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "media";
};

export type EventReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "event";
};

export type BusinessInfoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "businessInfo";
};

export type LegalReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "legal";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?:
    | HomeReference
    | AboutReference
    | MediaReference
    | EventReference
    | BusinessInfoReference
    | LegalReference;
  language?: string;
};

export type Legal = {
  _id: string;
  _type: "legal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  termsText?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BusinessInfo = {
  _id: string;
  _type: "businessInfo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alttext?: string;
    _type: "image";
  };
  location?: string;
  phone?: string;
  email?: string;
  socials?: {
    twitter?: string;
    instagram?: string;
    facebook?: string;
    tiktok?: string;
    spotify?: string;
    youtube?: string;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  datetime?: string;
  cost?: number;
  location?: string;
  media?: Array<
    {
      _key: string;
    } & MediaReference
  >;
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  bannerText?: string;
  aboutText?: string;
  historyText?: string;
  hostText?: string;
  hostImage?: MediaReference;
  inspoText?: string;
  inspoImage?: MediaReference;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heroTitle?: string;
  heroImage?: MediaReference;
  heroSubtitle?: string;
  introText?: string;
};

export type Media = {
  _id: string;
  _type: "media";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  name?: string;
  file?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alttext?: string;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | TranslationMetadata
  | InternationalizedArrayReference
  | HomeReference
  | AboutReference
  | MediaReference
  | EventReference
  | BusinessInfoReference
  | LegalReference
  | InternationalizedArrayReferenceValue
  | Legal
  | SanityImageAssetReference
  | BusinessInfo
  | SanityImageCrop
  | SanityImageHotspot
  | Event
  | About
  | Home
  | Media
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/sanity/lib/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "about"][0] {_id, bannerText, aboutText, historyText, hostText, inspoText, hostImage-> {_id,      file}, inspoImage-> {_id,      file}}
export type ABOUT_QUERY_RESULT = {
  _id: string;
  bannerText: string | null;
  aboutText: string | null;
  historyText: string | null;
  hostText: string | null;
  inspoText: string | null;
  hostImage: {
    _id: string;
    file: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alttext?: string;
      _type: "image";
    } | null;
  } | null;
  inspoImage: {
    _id: string;
    file: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alttext?: string;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: EVENTS_QUERY
// Query: *[_type == "event"] | order(datetime desc) {_id, title, description, cost,      media[]->{      _id,      file    }, datetime, location}
export type EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  cost: number | null;
  media: Array<{
    _id: string;
    file: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alttext?: string;
      _type: "image";
    } | null;
  }> | null;
  datetime: string | null;
  location: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == 'home'] [0]{_id, heroSubtitle, heroTitle, introText, heroImage-> {_id,      file}}
export type HOMEPAGE_QUERY_RESULT = {
  _id: string;
  heroSubtitle: string | null;
  heroTitle: string | null;
  introText: string | null;
  heroImage: {
    _id: string;
    file: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alttext?: string;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: LEGAL_QUERY
// Query: *[_type == 'legal'][0] {_id, title, termsText}
export type LEGAL_QUERY_RESULT = {
  _id: string;
  title: string | null;
  termsText: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: BUSINESS_QUERY
// Query: *[_type == 'busninessInfo'][0] {_id, name, description, logo[]->{      _id,      file },      location, phone, email, socials[]->{      _id,      icon,      url    }}
export type BUSINESS_QUERY_RESULT = null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "about"][0] {_id, bannerText, aboutText, historyText, hostText, inspoText, hostImage-> {_id,\n      file}, inspoImage-> {_id,\n      file}}': ABOUT_QUERY_RESULT;
    '*[_type == "event"] | order(datetime desc) {_id, title, description, cost,  \n    media[]->{\n      _id,\n      file\n    }, datetime, location}': EVENTS_QUERY_RESULT;
    "*[_type == 'home'] [0]{_id, heroSubtitle, heroTitle, introText, heroImage-> {_id,\n      file}}": HOMEPAGE_QUERY_RESULT;
    "*[_type == 'legal'][0] {_id, title, termsText}": LEGAL_QUERY_RESULT;
    "*[_type == 'busninessInfo'][0] {_id, name, description, logo[]->{\n      _id,\n      file },\n      location, phone, email, socials[]->{\n      _id,\n      icon,\n      url\n    }}": BUSINESS_QUERY_RESULT;
  }
}
